add_newline = false

[hostname]
ssh_only = true
format = 'on [$ssh_symbol$hostname](bold yellow) '

[character]
success_symbol = "[󰁕 ](bold green)"
error_symbol = "[✗ ](bold red)"
vimcmd_symbol = "[󰁎 ](bold green)"
vimcmd_replace_one_symbol = "[󰁎 ](bold purple)"
vimcmd_replace_symbol = "[󰁎 ](bold purple)"
vimcmd_visual_symbol = "[󰁎 ](bold purple)"

[directory]
style = "bold italic cyan"

[cmd_duration]
style = "italic yellow"
