# Don't print a new line at the start of the prompt
add_newline = false

# Charakter config
[character]
format = "$symbol"
success_symbol = "[󰁕 ](bold green)"
error_symbol = "[✗ ](bold red) "
vicmd_symbol = "[󰁎 ](bold green)"
disabled = false

# Username settings
[username]
show_always = true
style_root = "bold red"
style_user = "bold yellow"
format = "[$user]($style) "
disabled = false

