local config = function()
	require("nvim-treesitter.configs").setup({
		ensure_installed = {
			"angular",
			"arduino",
			"astro",
			"awk",
			"bash",
			"bibtex",
			"bicep",
			"c",
			"clojure",
			"cmake",
			"commonlisp",
			"cpp",
			"css",
			"cuda",
			"diff",
			"dockerfile",
			"elixir",
			"elm",
			"erlang",
			"fish",
			"fortran",
			"git_config",
			"gitignore",
			"gitcommit",
			"go",
			"graphql",
			"groovy",
			"haskell",
			"hcl",
			"html",
			"java",
			"javascript",
			"jsdoc",
			"json",
			"json5",
			"jsonc",
			"jsonnet",
			"julia",
			"kotlin",
			"ledger",
			"lua",
			"luadoc",
			"luap",
			"make",
			"markdown",
			"markdown_inline",
			"matlab",
			"perl",
			"php",
			"pug",
			"puppet",
			"python",
			"query",
			"r",
			"regex",
			"ruby",
			"rust",
			"scala",
			"scss",
			"sql",
			"svelte",
			"terraform",
			"toml",
			"tsx",
			"typescript",
			"vim",
			"vimdoc",
			"vue",
			"wgsl",
			"xml",
			"yaml",
		},
		highlight = {
			enable = true,
		},
		indent = {
			enable = true,
		},
		incremental_selection = {
			enable = true,
			keymaps = {
				init_selection = "<C-space>",
				node_incremental = "<C-space>",
				scope_incremental = false,
				node_decremental = "<bs>",
			},
		},
		textobjects = {
			move = {
				enable = true,
				goto_next_start = { ["]f"] = "@function.outer", ["]c"] = "@class.outer" },
				goto_next_end = { ["]F"] = "@function.outer", ["]C"] = "@class.outer" },
				goto_previous_start = { ["[f"] = "@function.outer", ["[c"] = "@class.outer" },
				goto_previous_end = { ["[F"] = "@function.outer", ["[C"] = "@class.outer" },
			},
		},
	})
end

return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	lazy = false,
	config = config,
}
